/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication128;

/**
 *
 * @author Aspire
 */
import java.awt.Toolkit;
public class Main_Menu extends javax.swing.JFrame {

    /**
     * Creates new form Main_Menu
     */
    public Main_Menu() {
        initComponents();
         this.setLocation(600,200);
        initialize();
    }
     private void  initialize(){ 
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("$.PNG")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnCustomer = new javax.swing.JButton();
        btnAccount = new javax.swing.JButton();
        btnEmpolyeeInformation = new javax.swing.JButton();
        btnLoan = new javax.swing.JButton();
        btnCard = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MAIN_MENU\n");
        setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        setForeground(new java.awt.Color(0, 0, 0));
        setMinimumSize(new java.awt.Dimension(626, 700));
        getContentPane().setLayout(null);

        jButton1.setText("jButton1");
        getContentPane().add(jButton1);
        jButton1.setBounds(10, 532, 73, 0);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        btnCustomer.setBackground(new java.awt.Color(102, 191, 178));
        btnCustomer.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnCustomer.setText("CUSTOMER INFORMATION");
        btnCustomer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        btnCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomerActionPerformed(evt);
            }
        });
        jPanel1.add(btnCustomer);
        btnCustomer.setBounds(158, 36, 338, 60);

        btnAccount.setBackground(new java.awt.Color(102, 192, 178));
        btnAccount.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnAccount.setText("ACCOUNT INFORMATION");
        btnAccount.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        btnAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccountActionPerformed(evt);
            }
        });
        jPanel1.add(btnAccount);
        btnAccount.setBounds(158, 107, 338, 66);

        btnEmpolyeeInformation.setBackground(new java.awt.Color(102, 191, 178));
        btnEmpolyeeInformation.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnEmpolyeeInformation.setText("EMPLOYEE INFORMATION");
        btnEmpolyeeInformation.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        btnEmpolyeeInformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpolyeeInformationActionPerformed(evt);
            }
        });
        jPanel1.add(btnEmpolyeeInformation);
        btnEmpolyeeInformation.setBounds(158, 191, 338, 67);

        btnLoan.setBackground(new java.awt.Color(102, 191, 178));
        btnLoan.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnLoan.setText("LOAN INFORMATION");
        btnLoan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        btnLoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoanActionPerformed(evt);
            }
        });
        jPanel1.add(btnLoan);
        btnLoan.setBounds(158, 276, 338, 66);

        btnCard.setBackground(new java.awt.Color(102, 191, 178));
        btnCard.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnCard.setText("CARD INFORMATIONS");
        btnCard.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        btnCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCardActionPerformed(evt);
            }
        });
        jPanel1.add(btnCard);
        btnCard.setBounds(158, 360, 338, 62);

        jButton2.setBackground(new java.awt.Color(0, 153, 153));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton2.setText("EXIT");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel1.add(jButton2);
        jButton2.setBounds(278, 440, 93, 38);

        jLabel1.setIcon(new javax.swing.ImageIcon("E:\\1. database\\coin.png")); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 10, 720, 580);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(2, -4, 720, 550);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomerActionPerformed
        // TODO add your handling code here:
        NewJFrame nj = new NewJFrame();
        nj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCustomerActionPerformed

    private void btnAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccountActionPerformed
        // TODO add your handling code here:
        account ac =new account();
        ac.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAccountActionPerformed

    private void btnEmpolyeeInformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpolyeeInformationActionPerformed
        // TODO add your handling code here:
        employee emp = new employee();
        emp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnEmpolyeeInformationActionPerformed

    private void btnLoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoanActionPerformed
        // TODO add your handling code here:
        Loan l= new Loan();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLoanActionPerformed

    private void btnCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCardActionPerformed
        // TODO add your handling code here:
        Card c=new Card();
        c.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCardActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccount;
    private javax.swing.JButton btnCard;
    private javax.swing.JButton btnCustomer;
    private javax.swing.JButton btnEmpolyeeInformation;
    private javax.swing.JButton btnLoan;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
